### ISSUE TITLE
(5 hours) Proposal to Move 'auto-assign update points' checkbox to a more logical location.

### ISSUE THREAD

**Issue by jasperfirecai2** [dan-simon/misc#10]
I spent a decent few minutes looking for the checkbox between the other settings, and in the update tab, but couldn't find it. went digging in source code and was still tunnelvisioned.
I don't think (only) having it in the main tab makes a lot of sense

**Comment by dan-simon** [comment]
Thank you very much for reporting this! I think I just made a fix that displays it in both the main tab (as before) and update tab (and updates both checkboxes when either is toggled), but if this fix doesn't seem to work, if it somehow introduced another issue, or if this isn't a satisfactory solution in your opinion, please let me know.

**Comment by jasperfirecai2** [comment]
Thank you for the quick response, it seems to work and it's in a nice position!
