### ISSUE TITLE
(5 hours) Logarithmic challenge text overlaps rewards

### ISSUE THREAD

**Issue by jasperfirecai2** [dan-simon/misc#11]
![image](https://user-images.githubusercontent.com/8398131/87338096-dd54ed80-c544-11ea-9d6c-12eaf6d71404.png)
As the title says, the final bit of text from the logarithmic challenge overlaps the 'farthest reached' text of the rewards.
my personal easy-way-out suggestion would be to remove info on what dilation does from that box, but there's probably a better solution out there.

**Comment by jasperfirecai2** [comment]
sidenote: the colour scheme is from a browser extension, but this issue persists when i disable it and refresh

**Comment by dan-simon** [comment]
Thanks for reporting this! The easy-way-out I tend to use for this type of issue is make the challenge button bigger (in this case, taller). If I didn't make it bigger by enough, let me know. On my computer this makes it barely possible to see total challenges completed and each individual challenge's times completed at the same time, which I think is acceptable if not ideal; if making the button bigger created severe display issues for you, let me know.
