### ISSUE TITLE
2 complexity auto buyers freezes game

### ISSUE THREAD

**Issue by inconsistent-brick** [dan-simon/misc#14]
file: https://github.com/dan-simon/misc/blob/master/fe000000/js/autobuyers.js lines 337 & 340
'Time past peak/sec'  
'Fraction of peak/sec'
use  shouldComplexity = ComplexityPrestigeLayer.eternityPointGain()
should use ComplexityPrestigeLayer.complexityPointGain() like other complexity auto buyers

**Comment by dan-simon** [comment]
Sorry for not fixing this until now. It should be fixed now by https://github.com/dan-simon/misc/commit/7d817fe6fdebbc383ce553a5c92d599603538bf7 . Thanks for the suggested fix!
