### ISSUE TITLE
(fe000000) Higher precision never getting used

### ISSUE THREAD

**Issue by 1e1000000** [dan-simon/misc#16]
10:
![image](https://user-images.githubusercontent.com/54700438/144736580-21df06b8-008a-4b1b-92d4-403bad54d725.png)
Expected: number will be longer than actual

0:
![image](https://user-images.githubusercontent.com/54700438/144736591-4768b7a1-6ece-4a6d-b79b-adb7ababe163.png)
Expected: number will be shorter than actual

**Comment by dan-simon** [comment]
I think the higher precision is used for numbers that need a lot of precision, like Normal Challenge 3 multiplier to Generator 1. There's a significant chance that I'll add more description about this somewhere since it's been asked about before.

**Comment by dan-simon** [comment]
I added a description. Please let me know if this does not solve the issue, and if so explain why. Otherwise I'll close it soon.

**Comment by 1e1000000** [comment]
Anyway, can Higher precision option affect exponent part of number formatting after ee9 for scientific and similar notation?

**Comment by dan-simon** [comment]
It's possible that I might add a third setting for precision on high numbers (probably unlocking with chroma, since that's when it'd start to be useful) but it won't be the current higher precision and I'm unlikely to add it.
