### ISSUE TITLE
How does liquification work in Infinite Layers?

### ISSUE THREAD

**Issue by hypcos** [dan-simon/misc#19]
It seems that the liquificated prestige layer keep only one generator - the first generator of that prestige layer. But how does the amount/multiplier/cost work?

**Comment by dan-simon** [comment]
It's been a very long time and I don't have a save that far in, but I believe what happens is the base multiplier is the multiplier that the first generator would have from purchases (with a usual cost calculation for it) and the total multiplier is that base multiplier squared (accounting for all purchase multipliers) times multipliers on all generators raised to the power of how many generators you would have (basically log(log(currency))) to the power of 1.0001 (to give a small benefit to liquification). See <https://github.com/dan-simon/misc/blob/master/b2/js/liquification.js> I'm not sure how amount of the first generator works but it's fairly clearly small enough not to matter.

**Comment by hypcos** [comment]
So it should be this way?

Generally, for a usual prestige layer, the program simulate the growth of generators, even if it is fully automatic. But for a liquified layer, the program will use some math approximation instead of simulation, reducing the time of calculation through many generators. Apparently multipliers of all generators (if this layer were a usual layer) pile into Generator 1.
Multiplier source: (1) buy-multiplier, (2) multipliers from higher prestige layers, (3) multipliers from incrementali, and (4) a special modification from singularity.

Now think about the amount of Generator 1 of a usual layer. It's approximately the amount*multiplier of Generator 2, but with a time dependent factor. Back to the case of liquified layer. "amount*multiplier of Generator 2" is already calculated within the multiplier of Generator 1, so we kick out that. The leftover is time factor. "Time factor = 1" means "without Generator 2 changing its amount*multiplier, after 1s of production, Generator 1 amount will increase by that many". That's quite a complicated factor. But generally, quicker growth of multiplier source will lead to smaller time factor because the older production worth less time under latest multiplier; waiting (as the progress slow down) will lead to bigger time factor.

I haven't found the source code for how does the amount of Generator 1 of a liquified layer work, but it seems to be constant over time (or, it just increase as you buy the Generator 1).

**Comment by dan-simon** [comment]
Yeah, that seems basically right (sorry for not responding to this, I didn't see the GitHub notification). The key thing is that though the time factor is complicated, the numbers are so big by the time liquification happens that the power of 1.0001 more than compensates for the time factor (which is like 1e6^1000 = 1e6000 even in the most extreme case, and most cases are less than that). So we just ignore the time factor on everything but Generator 1.

**Comment by dan-simon** [comment]
Gonna close this, please create a new issue or reopen if you have more questions.
