### ISSUE TITLE
Requesting a breakdown of complexity achievements order and their required challenge completions

### ISSUE THREAD

**Issue by jolitti** [dan-simon/misc#20]
Like the guide does for eternity challenges, it would be really convenient to have a quick reference for complexity achievements
Something like `3/10/5/0/0/0 Forever isn't too long`, where the first string of numbers is the corresponding recommended number of CC completions

**Comment by dan-simon** [comment]
I did this in the guide, when GitHub refreshes in a few minutes it should be visible. Let me know if you have any issues; if not, I'll close this after about a day

**Comment by jolitti** [comment]
Thank you a bunch! I also want to use this occasion to thank you for making such an interesting incremental
