### ISSUE TITLE
[5 hours][suggestions] Improve assigning developers

### ISSUE THREAD

**Issue by mazunki** [dan-simon/misc#23]
Found the 5 hours game some days ago, it's actually quite fun, except the UI for assigning workers to tasks is annoying. The buttons are quite small, and require you to either assign max, or do one at a time. Making the buttons larger, and allowing a percentage (e.g 10% of max) and/or a fixed higher value would make it much better.

Using update points to improve the worker assignation would probably be nice: Assigning percentages, assigning higher-than-one values, automatically assign 20% of available workers to all tasks, e.g.

I see the game hasn't been developed in two years, but i feel it shouldn't be too hard to implement. If you've left the game behind, I might consider looking into making a PR for some of these ideas sometime. :)

**Comment by dan-simon** [comment]
I've added +10 and -10, and also made the buttons bigger and (I know you didn't ask for this but I've seen other people want it) increased starting devs. I might close this issue in a few days.

**Comment by mazunki** [comment]
Thanks a bunch, it looks marvelous now. Cool beans. (I noticed the upgrade a bit after I posted the question, although the +10 is nice for the grinding gap)

Feel free to close it.
