### ISSUE TITLE
Display lowest/highest prestige layers

### ISSUE THREAD

**Issue by multivberse** [dan-simon/misc#7]
At the time of writing, I've played up to meta¹¹-eternity in this (mainly because it's a good way to kill time), and I've noticed that the game starts to lag pretty badly at this point, which is to be expected when updating 40+ layers simultaneously.

There's an option to display a set amount of the lowest and highest dimensions for each layer, which is convenient, but having a button to toggle each individual layer becomes really cluttered and tedious to work with when you get up to around where I am. 

Thus, I have a suggestion: add a similar option for the prestige layers as well as the dimensions - that way, it reduces lag, and saves the time it takes to turn all of the lower layers off. Not to mention said lower layers are all totally automated, so you only really need to focus on the three highest layers anyway.

**Comment by multivberse** [comment]
shoot this was meant to be in misc/b2


eh it's fine

**Comment by dan-simon** [comment]
I haven't touched Infinite Layers in a long time but I tried to fix this. I think I have saves that can test the fix but please mention it here if I introduce an additional bug, or if I didn't understand what you wanted.

**Comment by multivberse** [comment]
Since I reset my game after hitting the hardcap of e1.79e308, I had to play back up to the point where the fix appears. The [white text bug](https://github.com/dan-simon/misc/pull/3) occurs when the theme is set to "dark", but the feature otherwise works as intended.
